site_name: fetchu
site_description: Documentation for fetchu
site_author: imacodr
site_url: https://imacodr.github.io/fetchu

repo_name: imacodr/fetchu
repo_url: https://github.com/imacodr/fetchu

theme:
  logo: https://github.com/imacodr/fetchu/blob/main/assets/logo.png?raw=true
  favicon: /logo.png
  name: material
  palette:
    scheme: slate
    primary: red
